### ISSUE TITLE
Clean up the documentation

### ISSUE THREAD

**Issue by ghost** [beerisgood/Mobile_Security#7]
Right now, this page is a little messy. Down below there are a couple of ideas which try to “fix” this issue

- It would be make a clearly distinction between first parties and third parties documentation. E.g. First Google and Android stuff, and then GrapheneOS stuff. 
- Divide Android, IOS and Linux  in three different sections with sub sections like this:

## Linux 

- Add more information about the links. E.g who wrote it;

**Comment by beerisgood** [comment]
@jermanuts i close it for now.
But as I wrote you can send a PR if you want
